### ISSUE TITLE
Why don't you delete this repo? It shows up first on google search.

### ISSUE THREAD

**Issue by samedson** [Diogenesthecynic/FullScreenMario#135]

**Comment by JoshuaKGoldberg** [comment]
Honestly, no major reason. I would feel bad removing record of [the other contributors](https://github.com/JoshuaKGoldberg/FullScreenMario/graphs/contributors), and I hadn't considered SEO.

I'll rename it, that'll show them. :)

**Comment by samedson** [comment]
Awesome, good call
