### ISSUE TITLE
1-2 pipe isn't working

### ISSUE THREAD

**Issue by doronseg** [Diogenesthecynic/FullScreenMario#137]
The 1-2 pipe isn't working
as seen in this video:
https://doron-has.joined-the.club/MnVChOQZT.mp4 
Please fix it ASAP.

Doron

**Comment by JoshuaKGoldberg** [comment]
Hi @doron1803 - thanks for posting!

The README.md is accurate; this project isn't maintained anymore. 

Your .mp4 link is also a 404.
